export const forciblePseudoClasses = [
  "hover",
  "active",
  "focus",
  "focus-visible",
  "focus-within",
  "checked",
  "indeterminate",
  "target",
  "enabled",
  "disabled",
  "valid",
  "invalid",
  "required",
  "optional",
  "read-only",
  "read-write",
  "placeholder-shown",
  "user-invalid",
];

export const separators = [
  "child",
  "parent",
  "sibling",
  "adjacent",
  "descendant",
  "column-combinator",
];

export const inheritableProperties = [
  "azimuth",
  "border-collapse",
  "border-spacing",
  "caption-side",
  "color",
  "cursor",
  "direction",
  "elevation",
  "empty-cells",
  "font-family",
  "font-size",
  "font-style",
  "font-variant",
  "font-weight",
  "font",
  "letter-spacing",
  "line-height",
  "list-style-image",
  "list-style-position",
  "list-style-type",
  "list-style",
  "orphans",
  "pitch-range",
  "pitch",
  "quotes",
  "richness",
  "speak-header",
  "speak-numeral",
  "speak-punctuation",
  "speak",
  "speech-rate",
  "stress",
  "text-align",
  "text-indent",
  "text-transform",
  "visibility",
  "voice-family",
  "volume",
  "white-space",
  "widows",
  "word-spacing",
];

export enum CDPNodeType {
  ELEMENT_NODE = 1,
  //ATTRIBUTE_NODE = 2,
  TEXT_NODE = 3,
  //CDATA_SECTION_NODE = 4,
  //ENTITY_REFERENCE_NODE = 5,
  //ENTITY_NODE = 6,
  //PROCESSING_INSTRUCTION_NODE = 7,
  COMMENT_NODE = 8,
  DOCUMENT_NODE = 9,
  DOCUMENT_TYPE_NODE = 10,
  //DOCUMENT_FRAGMENT_NODE = 11,
  //NOTATION_NODE = 12,
}
